### PR TITLE
Vanilla webpack

### PR DESCRIPTION
**Pull request by vsaarinen**
Use vanilla Webpack to build JS files.

Note that this requires doing the following in order to not have React be included twice:
```shell
cd path_to_project_that_includes_this
cd node_modules/react
npm link
cd path_to_this_project
npm link react
```

I.e. use the including project's React library for this.

### CODE REVIEW

**Comment by vsaarinen** [comment]
This is still a work in progress. Works otherwise except for CSS styling.

**Comment by juhoojala** [comment]
The npm link step could probably be avoided by replacing thinks like this
```
react: path.resolve('./node_modules/react'),
```
with
```
react: require.resolve('react'),
```

**Comment by vsaarinen** [comment]
I'm not sure. This solution was based on these suggestions: https://discuss.reactjs.org/t/double-inclusion-of-react-for-peer-dependency/2814/4

**Comment by vsaarinen** [comment]
Continued in #3

**Pull request closed without merging**
